S ::= [<WHITESPACE>](route|node){[<WHITESPACE>]<BETWEEN_COMMAND>[<WHITESPACE>](route|node)}

node ::= nodeId (<'['> nodeText <']'>)?
nodeId ::= unquotedId
<unquotedId> ::= #'[a-zA-Z0-9_]+'
nodeText ::= unquotedText
<unquotedText> ::= #'[a-zA-Z0-9_](?:[a-zA-Z0-9_\s]*[a-zA-Z0-9_])?'
route ::= node [<WHITESPACE>] <EDGE_ARROW> [<WHITESPACE>] [<'|'>[<WHITESPACE>]routeText[<WHITESPACE>]<'|'>] [<WHITESPACE>] node
routeText ::= unquotedText

SEMI ::= ';'
NEWLINE ::= #'\r?\n'
BETWEEN_COMMAND ::= (SEMI|NEWLINE)+ 
EDGE_ARROW ::= "-->"
WHITESPACE ::= #"\s+"
