S ::= [<WHITESPACE>](route|node){[<WHITESPACE>]<BETWEEN_COMMAND>[<WHITESPACE>](route|node)}

node ::= node-id (<'['> node-text <']'>)?
node-id ::= unquoted-id
<unquoted-id> ::= #'[a-zA-Z0-9_]+'
node-text ::= unquoted-text
<unquoted-text> ::= #'[a-zA-Z0-9_](?:[a-zA-Z0-9_\s]*[a-zA-Z0-9_])?'
route ::= node [<WHITESPACE>] <EDGE_ARROW> [<WHITESPACE>] [<'|'>[<WHITESPACE>]route-text[<WHITESPACE>]<'|'>] [<WHITESPACE>] node
route-text ::= unquoted-text

SEMI ::= ';'
NEWLINE ::= #'\r?\n'
BETWEEN_COMMAND ::= (SEMI|NEWLINE)+ 
EDGE_ARROW ::= "-->"
WHITESPACE ::= #"\s+"
